import React from 'react';
import { FileText } from 'lucide-react';

const TermsPage = () => {
    return (
        <div className="bg-slate-50 min-h-screen pt-32 pb-20">
            <div className="container mx-auto px-6 max-w-4xl">
                <div className="bg-white p-8 md:p-16 rounded-3xl border border-slate-200 shadow-sm">
                    <div className="flex items-center gap-3 mb-8 pb-8 border-b border-slate-100">
                        <div className="w-12 h-12 bg-purple-50 rounded-full flex items-center justify-center text-purple-600">
                            <FileText size={24} />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
                            <p className="text-slate-500 text-sm">Last updated: October 26, 2023</p>
                        </div>
                    </div>

                    <div className="prose prose-slate max-w-none prose-headings:font-bold prose-headings:text-slate-900 prose-p:text-slate-600 prose-a:text-blue-600">
                        <p>Welcome to Wealth Matrix. Please read these Terms of Service carefully before using our platform.</p>

                        <h3>1. Acceptance of Terms</h3>
                        <p>
                            By accessing or using our service, you agree to be bound by these terms. If you disagree with any part of the terms, you may not access the service.
                        </p>

                        <h3>2. Description of Service</h3>
                        <p>
                            Wealth Matrix provides AI-powered financial calculation tools. These tools are for informational purposes only and do not constitute financial advice.
                        </p>

                        <h3>3. User Representations</h3>
                        <p>
                            By using the Site, you represent and warrant that: (1) all registration information you submit will be true,
                            accurate, current, and complete; (2) you will maintain the accuracy of such information.
                        </p>

                        <h3>4. Purchasing Credits</h3>
                        <p>
                            Credits purchased on Wealth Matrix are non-transferable. We reserve the right to change our pricing at any time.
                            Refunds are available within 14 days of purchase for unused credits only.
                        </p>

                        <h3>5. Disclaimer</h3>
                        <p>
                            The financial projections generated by our AI tools are for informational purposes only and do not constitute
                            professional financial advice. Users should consult with a qualified financial advisor before making investment decisions.
                        </p>

                        <h3>6. Limitation of Liability</h3>
                        <p>
                            In no event shall Wealth Matrix, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any
                            indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits.
                        </p>

                        <div className="mt-8 p-6 bg-slate-50 rounded-xl border border-slate-100">
                            <p className="text-sm mb-0">
                                <strong>Questions?</strong> Please contact us at <a href="mailto:legal@wealthmatrix.com">legal@wealthmatrix.com</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsPage;
